### ISSUE TITLE
Cycle through game info

### ISSUE THREAD

**Issue by rincew1nd** [Hotbrawl20/XCI-Reader#1]
Here is a fix for the bad code on https://github.com/Hotbrawl20/XCI-Reader/blob/e3e6e73c70e648f6bace72c34d8b672990a3d2b5/Secret%20Switch%20reader/Form1.cs#L149

Right now you hardcoded parsing of all games info in xml (Ridiculous :D) and after adding new ones you have to update program too. It's really bad design choice.
Just use xPath properly next time or learn them. They will help you a lot.
https://gist.github.com/rincew1nd/397b8f26be9b72569051068f2ed0c6e8

P.S. Please, debug it before releasing. I have no possibility to test it myself in you project right now (old VS).

**Comment by Hotbrawl20** [comment]
about the debugin: i tested it with 5 different roms, all worked. i just have to update it till i manage to fix that information reading. I hope i can fix this soon. Thanks for sending the fix

**Comment by rincew1nd** [comment]
> about the debugin: i tested it with 5 different roms, all worked. i just have to update it till i manage to fix that information reading.
I mean debug my code sketch before using it in release version :)

**Comment by NicoAICP** [comment]
it works now, thanks for the help. Its included in the newest release but a bit different.
